- hosts: all
  become: true
  roles:
    - commons

- hosts: router
  become: true
  roles:
    - router
    - dhcp

- hosts: web
  become: true
  roles:
    - web

- hosts: web
  become: true
  roles:
    - clientes

- hosts: cliente
  become: true
  roles:
    - clientes

- hosts: all
  become: true
  roles:
    - reboot